### ISSUE TITLE
#1 Conflito entre threads ao abrir a janela do simulador pelo Portugol

### ISSUE THREAD

**Issue by douglasbreda** [douglasbreda/SimuladorExperimentos#1]
EDT violation detected

`br.simulador.plugin.biblioteca.base.Agente$1[,0,0,0x0,invalid,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]
	at java.lang.Thread.getStackTrace(Thread.java:1559)
	at br.univali.ps.DetectorViolacoesThreadSwing.checkThreadViolations(DetectorViolacoesThreadSwing.java:100)
	at br.univali.ps.DetectorViolacoesThreadSwing.addDirtyRegion(DetectorViolacoesThreadSwing.java:88)
	at javax.swing.JComponent.repaint(JComponent.java:4793)
	at java.awt.Component.repaint(Component.java:3311)
	at javax.swing.JComponent.setFont(JComponent.java:2758)
	at javax.swing.LookAndFeel.installColorsAndFont(LookAndFeel.java:208)
	at javax.swing.plaf.basic.BasicPanelUI.installDefaults(BasicPanelUI.java:66)
	at javax.swing.plaf.basic.BasicPanelUI.installUI(BasicPanelUI.java:56)
	at com.alee.laf.panel.WebPanelUI.installUI(WebPanelUI.java:99)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JPanel.setUI(JPanel.java:153)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at br.simulador.plugin.biblioteca.base.Agente$1.<init>(Agente.java:26)
	at br.simulador.plugin.biblioteca.base.Agente.criarFormaAgente(Agente.java:26)
	at br.simulador.plugin.biblioteca.base.Agente.<init>(Agente.java:22)
	at br.simulador.gerenciadores.GerenciadorExecucao.criar_agentes(GerenciadorExecucao.java:152)
	at br.simulador.plugin.biblioteca.Experimentos.criar_agentes(Experimentos.java:35)
	at programas.Programa1506899689153.executar(Programa1506899689153.java:31)
	at br.univali.portugol.nucleo.Programa$TarefaExecucao.run(Programa.java:675)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
 [br.univali.ps.DetectorViolacoesThreadSwing violationFound]  `

**Comment by Ailtonjr** [comment]
Estou com o mesmo problema 😢
